import type { Track } from "@/lib/music-data";

/** 华语曲库：流行 / 民谣 / 抒情 / 轻音乐，风格参考网易云、QQ 音乐常见歌单 */
export const chineseMusicCatalog: Track[] = [
  // —— 深夜 · 孤独 · 内省 ——
  {
    id: "cn-pop-01",
    title: "像我这样的人",
    artist: "毛不易",
    genre: "流行",
    style: "民谣流行",
    duration: "4:27",
    mood: ["孤独", "内省", "深夜", "平静"],
    scenes: ["深夜独处", "加班", "emo", "自省", "孤独"],
    category: "深夜情绪",
    platform: "网易云音乐",
    gradient: "from-slate-700 via-indigo-900 to-violet-950",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
  },
  {
    id: "cn-pop-02",
    title: "消愁",
    artist: "毛不易",
    genre: "流行",
    style: "民谣流行",
    duration: "4:21",
    mood: ["伤感", "深夜", "叙事", "低沉"],
    scenes: ["喝酒", "深夜", "难过", "孤独", "回忆"],
    category: "深夜情绪",
    platform: "网易云音乐",
    gradient: "from-gray-800 via-slate-800 to-indigo-900",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
  },
  {
    id: "cn-pop-03",
    title: "十年",
    artist: "陈奕迅",
    genre: "流行",
    style: "抒情流行",
    duration: "3:25",
    mood: ["怀旧", "伤感", "分手", "抒情"],
    scenes: ["分手", "回忆", "失恋", "十年", "遗憾"],
    category: "失恋疗愈",
    platform: "QQ音乐",
    gradient: "from-amber-900 via-stone-800 to-neutral-900",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
  },
  {
    id: "cn-pop-04",
    title: "体面",
    artist: "于文文",
    genre: "流行",
    style: "抒情流行",
    duration: "4:12",
    mood: ["分手", "伤感", "克制", "抒情"],
    scenes: ["分手", "失恋", "体面告别", "难过"],
    category: "失恋疗愈",
    platform: "网易云音乐",
    gradient: "from-rose-900 via-red-950 to-stone-900",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
  },
  {
    id: "cn-pop-05",
    title: "后来",
    artist: "刘若英",
    genre: "流行",
    style: "抒情流行",
    duration: "5:41",
    mood: ["怀旧", "遗憾", "伤感", "温柔"],
    scenes: ["回忆", "初恋", "后悔", "失恋", "成长"],
    category: "失恋疗愈",
    platform: "QQ音乐",
    gradient: "from-pink-900 via-rose-900 to-violet-950",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
  },
  {
    id: "cn-pop-06",
    title: "泡沫",
    artist: "G.E.M. 邓紫棋",
    genre: "流行",
    style: "抒情流行",
    duration: "4:18",
    mood: ["伤感", "抒情", "爆发", "脆弱"],
    scenes: ["失恋", "分手", "心碎", "眼泪"],
    category: "失恋疗愈",
    platform: "QQ音乐",
    gradient: "from-fuchsia-800 via-purple-900 to-indigo-950",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
  },

  // —— 治愈 · 温暖 · 希望 ——
  {
    id: "cn-pop-07",
    title: "平凡之路",
    artist: "朴树",
    genre: "流行",
    style: "民谣摇滚",
    duration: "5:01",
    mood: ["治愈", "沉稳", "希望", "人生"],
    scenes: ["旅行", "治愈", "迷茫", "成长", "公路"],
    category: "治愈温暖",
    platform: "网易云音乐",
    gradient: "from-amber-600 via-orange-700 to-yellow-800",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
  },
  {
    id: "cn-pop-08",
    title: "起风了",
    artist: "买辣椒也用券",
    genre: "流行",
    style: "民谣流行",
    duration: "5:25",
    mood: ["治愈", "怀旧", "励志", "温柔"],
    scenes: ["毕业", "青春", "回忆", "成长", "治愈"],
    category: "治愈温暖",
    platform: "网易云音乐",
    gradient: "from-sky-500 via-cyan-600 to-teal-700",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
  },
  {
    id: "cn-pop-09",
    title: "稻香",
    artist: "周杰伦",
    genre: "流行",
    style: "流行",
    duration: "3:43",
    mood: ["温暖", "治愈", "童年", "轻快"],
    scenes: ["回家", "童年", "放松", "快乐", "田园"],
    category: "治愈温暖",
    platform: "QQ音乐",
    gradient: "from-lime-600 via-green-600 to-emerald-700",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
  },
  {
    id: "cn-pop-10",
    title: "岁月神偷",
    artist: "金玟岐",
    genre: "流行",
    style: "民谣流行",
    duration: "4:40",
    mood: ["温柔", "治愈", "时间", "细腻"],
    scenes: ["治愈", "安静", "温柔", "岁月", "陪伴"],
    category: "治愈温暖",
    platform: "网易云音乐",
    gradient: "from-rose-400 via-pink-300 to-amber-200",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
  },
  {
    id: "cn-pop-11",
    title: "世间美好与你环环相扣",
    artist: "柏松",
    genre: "流行",
    style: "民谣流行",
    duration: "4:09",
    mood: ["温暖", "浪漫", "治愈", "希望"],
    scenes: ["恋爱", "温暖", "治愈", "日常", "幸福"],
    category: "治愈温暖",
    platform: "网易云音乐",
    gradient: "from-orange-400 via-amber-400 to-yellow-300",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
  },
  {
    id: "cn-pop-12",
    title: "大鱼",
    artist: "周深",
    genre: "流行",
    style: "空灵流行",
    duration: "5:45",
    mood: ["空灵", "治愈", "深情", "影视"],
    scenes: ["安静", "治愈", "深情", "夜晚", "沉浸"],
    category: "治愈温暖",
    platform: "QQ音乐",
    gradient: "from-cyan-600 via-blue-700 to-indigo-800",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
  },

  // —— 浪漫 · 甜蜜 · 青春 ——
  {
    id: "cn-pop-13",
    title: "告白气球",
    artist: "周杰伦",
    genre: "流行",
    style: "甜蜜流行",
    duration: "3:35",
    mood: ["浪漫", "甜蜜", "轻快", "幸福"],
    scenes: ["约会", "恋爱", "表白", "甜蜜", "浪漫"],
    category: "浪漫甜蜜",
    platform: "QQ音乐",
    gradient: "from-pink-500 via-rose-400 to-red-400",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
  },
  {
    id: "cn-pop-14",
    title: "小幸运",
    artist: "田馥甄",
    genre: "流行",
    style: "抒情流行",
    duration: "4:23",
    mood: ["青春", "浪漫", "甜蜜", "怀旧"],
    scenes: ["校园", "暗恋", "青春", "恋爱", "回忆"],
    category: "浪漫甜蜜",
    platform: "网易云音乐",
    gradient: "from-yellow-300 via-amber-300 to-orange-400",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
  },
  {
    id: "cn-pop-15",
    title: "慢慢喜欢你",
    artist: "莫文蔚",
    genre: "流行",
    style: "爵士流行",
    duration: "3:41",
    mood: ["浪漫", "温柔", "慵懒", "甜蜜"],
    scenes: ["约会", "恋爱", "温柔", "夜晚", "浪漫"],
    category: "浪漫甜蜜",
    platform: "QQ音乐",
    gradient: "from-rose-400 via-fuchsia-400 to-purple-500",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
  },
  {
    id: "cn-pop-16",
    title: "晴天",
    artist: "周杰伦",
    genre: "流行",
    style: "流行",
    duration: "4:29",
    mood: ["青春", "怀旧", "清新", "遗憾"],
    scenes: ["青春", "夏天", "校园", "回忆", "初恋"],
    category: "浪漫甜蜜",
    platform: "QQ音乐",
    gradient: "from-sky-400 via-blue-400 to-indigo-500",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
  },
  {
    id: "cn-pop-17",
    title: "追光者",
    artist: "岑宁儿",
    genre: "流行",
    style: "抒情流行",
    duration: "3:55",
    mood: ["温柔", "暗恋", "治愈", "细腻"],
    scenes: ["暗恋", "温柔", "治愈", "陪伴", "喜欢"],
    category: "浪漫甜蜜",
    platform: "网易云音乐",
    gradient: "from-violet-400 via-purple-400 to-fuchsia-400",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
  },

  // —— 民谣 · 城市 · 叙事 ——
  {
    id: "cn-folk-01",
    title: "成都",
    artist: "赵雷",
    genre: "民谣",
    style: "城市民谣",
    duration: "5:28",
    mood: ["温暖", "叙事", "城市", "怀旧"],
    scenes: ["旅行", "城市", "酒吧", "夜晚", "故事"],
    category: "民谣叙事",
    platform: "网易云音乐",
    gradient: "from-amber-700 via-orange-800 to-red-900",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
  },
  {
    id: "cn-folk-02",
    title: "南山南",
    artist: "马頔",
    genre: "民谣",
    style: "独立民谣",
    duration: "4:32",
    mood: ["忧郁", "叙事", "沉静", "文艺"],
    scenes: ["孤独", "文艺", "夜晚", "思念", "故事"],
    category: "民谣叙事",
    platform: "网易云音乐",
    gradient: "from-stone-700 via-zinc-800 to-slate-900",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
  },
  {
    id: "cn-folk-03",
    title: "理想三旬",
    artist: "陈鸿宇",
    genre: "民谣",
    style: "独立民谣",
    duration: "4:06",
    mood: ["沉静", "叙事", "文艺", "低能量"],
    scenes: ["深夜", "文艺", "思考", "独处", "岁月"],
    category: "民谣叙事",
    platform: "网易云音乐",
    gradient: "from-stone-600 via-amber-800 to-orange-900",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
  },
  {
    id: "cn-folk-04",
    title: "这一生关于你的风景",
    artist: "隔壁老樊",
    genre: "民谣",
    style: "民谣流行",
    duration: "4:18",
    mood: ["治愈", "温柔", "叙事", "深情"],
    scenes: ["治愈", "思念", "风景", "温柔", "陪伴"],
    category: "民谣叙事",
    platform: "网易云音乐",
    gradient: "from-teal-600 via-emerald-600 to-green-700",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
  },

  // —— 励志 · 热血 · 力量 ——
  {
    id: "cn-rock-01",
    title: "夜空中最亮的星",
    artist: "逃跑计划",
    genre: "摇滚",
    style: "独立摇滚",
    duration: "4:12",
    mood: ["励志", "希望", "力量", "温暖"],
    scenes: ["励志", "梦想", "坚持", "希望", "奋斗"],
    category: "励志力量",
    platform: "QQ音乐",
    gradient: "from-indigo-600 via-blue-700 to-violet-800",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
  },
  {
    id: "cn-rock-02",
    title: "追梦赤子心",
    artist: "GALA",
    genre: "摇滚",
    style: "流行摇滚",
    duration: "5:20",
    mood: ["热血", "励志", "振奋", "高能量"],
    scenes: ["运动", "奋斗", "热血", "青春", "拼搏"],
    category: "励志力量",
    platform: "QQ音乐",
    gradient: "from-red-600 via-orange-600 to-amber-500",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
  },
  {
    id: "cn-rock-03",
    title: "孤勇者",
    artist: "陈奕迅",
    genre: "流行",
    style: "流行摇滚",
    duration: "4:16",
    mood: ["力量", "励志", "坚定", "高能量"],
    scenes: ["奋斗", "逆境", "坚持", "力量", "成长"],
    category: "励志力量",
    platform: "QQ音乐",
    gradient: "from-slate-800 via-gray-900 to-black",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
  },
  {
    id: "cn-rock-04",
    title: "光年之外",
    artist: "G.E.M. 邓紫棋",
    genre: "流行",
    style: "流行摇滚",
    duration: "3:55",
    mood: ["力量", "深情", "太空", "励志"],
    scenes: ["励志", "爱情", "力量", "科幻", "深情"],
    category: "励志力量",
    platform: "QQ音乐",
    gradient: "from-purple-600 via-violet-700 to-indigo-900",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
  },

  // —— 学习 · 专注 · 轻音乐 ——
  {
    id: "cn-light-01",
    title: "城南花已开",
    artist: "三亩地",
    genre: "轻音乐",
    style: "治愈纯音乐",
    duration: "4:32",
    mood: ["治愈", "温柔", "钢琴", "平静"],
    scenes: ["学习", "专注", "治愈", "安静", "放松"],
    category: "自习轻音乐",
    platform: "网易云音乐",
    gradient: "from-rose-500 via-pink-400 to-violet-500",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
  },
  {
    id: "cn-light-02",
    title: "夜的钢琴曲五",
    artist: "石进",
    genre: "轻音乐",
    style: "钢琴独奏",
    duration: "4:48",
    mood: ["钢琴", "抒情", "夜晚", "平静"],
    scenes: ["深夜学习", "专注", "钢琴", "安静", "工作"],
    category: "自习轻音乐",
    platform: "网易云音乐",
    gradient: "from-violet-700 via-purple-600 to-fuchsia-700",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
  },
  {
    id: "cn-light-03",
    title: "风居住的街道",
    artist: "矶村由纪子",
    genre: "轻音乐",
    style: "器乐",
    duration: "4:42",
    mood: ["空灵", "治愈", "东方", "平静"],
    scenes: ["冥想", "专注", "治愈", "安静", "阅读"],
    category: "自习轻音乐",
    platform: "QQ音乐",
    gradient: "from-teal-500 via-cyan-400 to-blue-500",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
  },

  // —— 国风 · 影视 ——
  {
    id: "cn-gf-01",
    title: "知否知否",
    artist: "胡夏 / 郁可唯",
    genre: "国风",
    style: "影视原声",
    duration: "4:30",
    mood: ["古风", "温柔", "叙事", "治愈"],
    scenes: ["古风", "安静", "追剧", "温柔", "岁月"],
    category: "国风影视",
    platform: "QQ音乐",
    gradient: "from-emerald-700 via-teal-700 to-cyan-800",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
  },
  {
    id: "cn-gf-02",
    title: "年轮",
    artist: "张碧晨",
    genre: "流行",
    style: "影视原声",
    duration: "4:32",
    mood: ["伤感", "古风", "深情", "影视"],
    scenes: ["古风", "伤感", "追剧", "深情", "遗憾"],
    category: "国风影视",
    platform: "QQ音乐",
    gradient: "from-amber-800 via-yellow-900 to-orange-950",
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
  },
];
